config/routes.rb
Rails.application.routes.draw do
  root :to =>'pages#home'
  resources :reservations
  resources :flights
  resources :airplanes

  resources :users, :only =>[:new, :create, :index]
  get'/login' => 'session#new'
  post'/login' => 'session#create'
  delete'/login' => 'session#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
 <div id="nav">
    <ul>
       <nav>
           <li>
                <%= link_to root_path do %> 
                    <%= image_tag 'logo.png' , :class=>'navbar-brand'%>
                <% end %>
            </li>
        
        <% if @current_user.present? %>
        
                    
            <li >
                <%= link_to 'Airplanes', airplanes_path  %>
            </li>

            <li >
                <%= link_to 'Reservations',reservations_path %>
            </li>

            <li >
                <%= link_to 'Flights', flights_path %>
            </li>

            <li >
                <%= link_to 'New Flight', new_flight_path %>
            </li>

            <li >
                <%= link_to "Logout #{ @current_user.name }", login_path, :method => 'delete'   %>
            </li>
                        
           
        <% else %>

            <li >
                <%= link_to "Sign Up", new_user_path  %>  
            </li>
                                
            <li >
                <%= link_to "Login", login_path  %>
            </li>
        <% end %>
        </nav>
    </ul>
</div>